services:
  - type: web
    name: thai-digit-recognizer
    runtime: python
    rootDir: app
    buildCommand: pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: "true"
